server:
  port: 2002
  context-path: /
  
eureka: 
  instance:
    # 单机 hostname: localhost #eureka注册中心实例名称
    hostname: eureka2002.etjava.com # 集群
  client: 
    #false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    register-with-eureka: false     
    #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    fetch-registry: false     
    service-url: 
      # 集群
      defaultZone: http://eureka2000.etjava.com:2000/eureka/,http://eureka2001.etjava.com:2001/eureka/ 
      #单机defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka注册中心交互的地址，查询服务和注册服务用到     