spring: 
  application:
    name: student-consumer-config
    
# ribbon 相关配置
#eureka:
#  client:
#    #register-with-eureka: false  由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以设置为false
#    register-with-eureka: false 
#    service-url: 
#      defaultZone: http://localhost:2004/eureka/


# 单机 需要指定服务提供者的IP+端口
# provider_host: http://localhost:1001

# 集群版 STUDENT-PROVIDER22 对应的是服务提供者配置文件中的application.name的值 
# 这里只能使用中划线 不能使用下划线 提供者那边也只能使用中划线
provider_host: http://MICROSERVICE-STUDENT