server:
  port: 2002
  context-path: /
  
eureka: 
  instance:
    # hostname: localhost 单机eureka注册中心实例名称 - 访问地址
    hostname: eureka2002.etjava.com #eureka注册中心实例名称 - 访问地址
  client: 
    register-with-eureka: false     #false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: false     #false 由于注册中心的职责就是维护服务实例，它并不需要去检索自己的服务，所以也设置为false(不需要检查自己是否存活状态)
    service-url: 
                    # 单机 设置与Eureka注册中心交互的地址，查询服务和注册服务用到(对外提供服务的访问地址)
       # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
                   # 集群  注意 不能注册到自己
       defaultZone: http://eureka2001.etjava.com:2001/eureka/,http://eureka2003.etjava.com:2003/eureka/