server: 
  port: 80
  context-path: /
  
# feign与hystrix整合  
feign: 
  hystrix: 
    enable: true

  
eureka:
  client:
    #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    register-with-eureka: false 
    service-url: 
      defaultZone: http://eureka2001.etjava.com:2001/eureka/,
                   http://eureka2002.etjava.com:2002/eureka/,
                   http://eureka2000.etjava.com:2000/eureka/
  